name: "phpunit"

on: [ push ]

permissions: read-all

jobs:
    laravel:
        runs-on: ubuntu-latest

        name: PHP Unit

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Install dependencies
                run: composer update

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
